[package]
name = "dfsdisc"
version = "0.1.0"
edition = "2018"
authors = ["Simon Harris <simon@pearfalse.com>"]

[lib]
name = "dfsdisc"
path = "src/lib.rs"

[[bin]]
name = "dfs"
path = "src/main.rs"

[dependencies]
ascii = ">= 0.8"
clap = "2.20"
arrayvec = "0.7.1"
